/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package javaapplication1;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author Thiago Vinícius
 */
public class AdicionarQuarto extends javax.swing.JFrame {
    
    JFrame parent;
    
    public AdicionarQuarto(JFrame parent) {
        this.parent = parent;       
        
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        nrDoQuarto = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        processar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setAlwaysOnTop(true);
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
        });

        jLabel1.setText("Nr. do Quarto:");

        processar.setText("Processar");
        processar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                processarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(nrDoQuarto, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(processar)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nrDoQuarto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(processar)
                    .addComponent(jLabel1))
                .addContainerGap(36, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
         parent.setEnabled(true);
         parent.toFront();
    }//GEN-LAST:event_formWindowClosed

    private void processarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_processarActionPerformed
        try{                       
            Connection con = DriverManager.getConnection("jdbc:derby://localhost:1527/Hotel", "root", "123456" );
        
            String sql = "INSERT INTO ROOT.QUARTOS (OCUPADO, NUMERO, CLIENTE, DATA_INICIAL, DATA_FINAL) VALUES (DEFAULT, ?, NULL, NULL, NULL)";
            PreparedStatement pstmt = con.prepareStatement(sql);             
            pstmt.setString(1, nrDoQuarto.getText());
            
            pstmt.execute();
            
            con.close();
            
            JOptionPane.showMessageDialog(this, "Quarto " + nrDoQuarto.getText() + " adicionado ao sistema", "", JOptionPane.INFORMATION_MESSAGE);
           
            //DISPOSE WINDOW
            parent.setEnabled(true);
            parent.toFront();
            this.dispose();

        }
        catch(SQLException ex){
            
        }
    }//GEN-LAST:event_processarActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextField nrDoQuarto;
    private javax.swing.JButton processar;
    // End of variables declaration//GEN-END:variables
}
