/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package javaapplication1;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.Vector;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author Thiago Vinícius
 */
public class AdicionarProdutoAConta extends javax.swing.JFrame {
    
    FecharConta parent;
    
    Vector<Vector<Object>> dadosDaTabela;
    
    public AdicionarProdutoAConta(FecharConta parent, Vector<Vector<Object>> dadosDaTabela) {
        this.parent = parent;       
        this.dadosDaTabela = dadosDaTabela;
        
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        processar = new javax.swing.JButton();
        comboBoxProduto = new javax.swing.JComboBox<>();
        buscarDados = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setAlwaysOnTop(true);
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
        });

        jLabel1.setText("Produto:");

        processar.setText("Processar");
        processar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                processarActionPerformed(evt);
            }
        });

        buscarDados.setText("Buscar Dados");
        buscarDados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscarDadosActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(comboBoxProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 19, Short.MAX_VALUE)
                .addComponent(processar)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(88, 88, 88)
                .addComponent(buscarDados)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(buscarDados, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(comboBoxProduto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(processar))
                .addContainerGap(43, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
         parent.setEnabled(true);
         parent.toFront();
         parent.updateTable();
    }//GEN-LAST:event_formWindowClosed

    private void processarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_processarActionPerformed
        try{
            Connection con = DriverManager.getConnection("jdbc:derby://localhost:1527/Hotel", "root", "123456" );

            PreparedStatement queryValor = con.prepareStatement("SELECT valor FROM produtos WHERE nome=?");    
            queryValor.setString(1, comboBoxProduto.getSelectedItem().toString());
            ResultSet rs = queryValor.executeQuery();
            rs.next();
                
            Vector<Object> temp = new Vector<Object>();
            
            temp.add(comboBoxProduto.getSelectedItem().toString());
            temp.add(rs.getDouble("valor"));            
            
            dadosDaTabela.add(temp);
            
            //DISPOSE WINDOW
            parent.setEnabled(true);
            parent.toFront();
            this.dispose();
            
            
            con.close();
        }
        catch(SQLException ex){

        }       
    }//GEN-LAST:event_processarActionPerformed

    private void buscarDadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscarDadosActionPerformed

        try{
            Connection con = DriverManager.getConnection("jdbc:derby://localhost:1527/Hotel", "root", "123456" );

            PreparedStatement query = con.prepareStatement("SELECT * FROM produtos WHERE nome!='Diária'");            
            ResultSet rs = query.executeQuery();

            comboBoxProduto.removeAllItems();
            
            while(rs.next()){
                comboBoxProduto.addItem(rs.getString("nome"));
            }
            
            con.close();
        }
        catch(SQLException ex){

        }

    }//GEN-LAST:event_buscarDadosActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buscarDados;
    private javax.swing.JComboBox<String> comboBoxProduto;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton processar;
    // End of variables declaration//GEN-END:variables
}
