/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package javaapplication1;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author Thiago Vinícius
 */
public class CancelarReserva extends javax.swing.JFrame {
    
    JFrame parent;
    
    public CancelarReserva(JFrame parent) {
        this.parent = parent;       
        
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        porNome = new javax.swing.JPanel();
        removerPorNome = new javax.swing.JButton();
        comboBoxNomes = new javax.swing.JComboBox<>();
        buscarDadosNomes = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        labelNrDoQuarto = new javax.swing.JLabel();
        porQuarto = new javax.swing.JPanel();
        buscarDadosNrQuarto = new javax.swing.JButton();
        comboBoxNrQuarto = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        removerPorNrQuarto = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        labelNomeDoCliente = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setAlwaysOnTop(true);
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
        });

        porNome.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        removerPorNome.setText("Cancela a reserva");
        removerPorNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removerPorNomeActionPerformed(evt);
            }
        });

        comboBoxNomes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboBoxNomesActionPerformed(evt);
            }
        });

        buscarDadosNomes.setText("Buscar Dados");
        buscarDadosNomes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscarDadosNomesActionPerformed(evt);
            }
        });

        jLabel2.setText("Cliente:");

        jLabel4.setText("Por Nome do Cliente:");

        jLabel6.setText("Quarto:");

        labelNrDoQuarto.setText("                    ");

        javax.swing.GroupLayout porNomeLayout = new javax.swing.GroupLayout(porNome);
        porNome.setLayout(porNomeLayout);
        porNomeLayout.setHorizontalGroup(
            porNomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(porNomeLayout.createSequentialGroup()
                .addGroup(porNomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(porNomeLayout.createSequentialGroup()
                        .addGap(148, 148, 148)
                        .addGroup(porNomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel4)
                            .addComponent(buscarDadosNomes)))
                    .addGroup(porNomeLayout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addGroup(porNomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel6))
                        .addGap(52, 52, 52)
                        .addGroup(porNomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelNrDoQuarto)
                            .addGroup(porNomeLayout.createSequentialGroup()
                                .addComponent(comboBoxNomes, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(26, 26, 26)
                                .addComponent(removerPorNome)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        porNomeLayout.setVerticalGroup(
            porNomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, porNomeLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 11, Short.MAX_VALUE)
                .addComponent(buscarDadosNomes, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(porNomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(comboBoxNomes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(removerPorNome))
                .addGap(18, 18, 18)
                .addGroup(porNomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(labelNrDoQuarto))
                .addContainerGap())
        );

        porQuarto.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        buscarDadosNrQuarto.setText("Buscar Dados");
        buscarDadosNrQuarto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscarDadosNrQuartoActionPerformed(evt);
            }
        });

        comboBoxNrQuarto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboBoxNrQuartoActionPerformed(evt);
            }
        });

        jLabel1.setText("Quarto:");

        removerPorNrQuarto.setText("Cancela a reserva");
        removerPorNrQuarto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removerPorNrQuartoActionPerformed(evt);
            }
        });

        jLabel3.setText("Por Nr. do Quarto:");

        jLabel5.setText("Reservado para:");

        labelNomeDoCliente.setText("                      ");

        javax.swing.GroupLayout porQuartoLayout = new javax.swing.GroupLayout(porQuarto);
        porQuarto.setLayout(porQuartoLayout);
        porQuartoLayout.setHorizontalGroup(
            porQuartoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(porQuartoLayout.createSequentialGroup()
                .addGroup(porQuartoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(porQuartoLayout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(jLabel1)
                        .addGap(53, 53, 53)
                        .addComponent(comboBoxNrQuarto, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26)
                        .addComponent(removerPorNrQuarto))
                    .addGroup(porQuartoLayout.createSequentialGroup()
                        .addGap(148, 148, 148)
                        .addGroup(porQuartoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(buscarDadosNrQuarto)))
                    .addGroup(porQuartoLayout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(labelNomeDoCliente)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        porQuartoLayout.setVerticalGroup(
            porQuartoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(porQuartoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(buscarDadosNrQuarto, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(porQuartoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(comboBoxNrQuarto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(removerPorNrQuarto))
                .addGap(18, 18, 18)
                .addGroup(porQuartoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(labelNomeDoCliente))
                .addContainerGap(23, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(porNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(porQuarto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(porNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(porQuarto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
         parent.setEnabled(true);
         parent.toFront();
    }//GEN-LAST:event_formWindowClosed

    private void removerPorNrQuartoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removerPorNrQuartoActionPerformed
        try{    
            if(comboBoxNrQuarto.getSelectedItem() != null){
            Connection con = DriverManager.getConnection("jdbc:derby://localhost:1527/Hotel", "root", "123456" );
            
            String sql = "UPDATE quartos SET ocupado=false, cliente=NULL, data_inicial=NULL, data_final=NULL WHERE numero=?";
            PreparedStatement pstmt = con.prepareStatement(sql);           
            pstmt.setString(1, comboBoxNrQuarto.getSelectedItem().toString());
            pstmt.executeUpdate();
            
            con.close();
            
            JOptionPane.showMessageDialog(this, "Reserva cancelada!", "", JOptionPane.INFORMATION_MESSAGE);
            //DISPOSE WINDOW
            parent.setEnabled(true);
            parent.toFront();
            this.dispose();
            }
            else{
                JOptionPane.showMessageDialog(this, "Selecione os dados da lista", "Erro", JOptionPane.ERROR_MESSAGE);                   
            }
        }
        catch(SQLException ex){
            
        }
    }//GEN-LAST:event_removerPorNrQuartoActionPerformed

    private void buscarDadosNrQuartoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscarDadosNrQuartoActionPerformed

        try{
            Connection con = DriverManager.getConnection("jdbc:derby://localhost:1527/Hotel", "root", "123456" );

            PreparedStatement nomesQuery = con.prepareStatement("SELECT * FROM ROOT.quartos WHERE ocupado=true AND cliente!=''");            
            ResultSet nomesrs = nomesQuery.executeQuery();

            comboBoxNrQuarto.removeAllItems();

            while(nomesrs.next()){
                comboBoxNrQuarto.addItem(nomesrs.getString("numero"));
            }

            con.close();            
        }
        catch(SQLException ex){

        }

    }//GEN-LAST:event_buscarDadosNrQuartoActionPerformed

    private void removerPorNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removerPorNomeActionPerformed
        try{    
            if(comboBoxNomes.getSelectedItem() != null){
                Connection con = DriverManager.getConnection("jdbc:derby://localhost:1527/Hotel", "root", "123456" );

                String sql = "UPDATE quartos SET ocupado=false, cliente=NULL, data_inicial=NULL, data_final=NULL WHERE cliente=?";
                PreparedStatement pstmt = con.prepareStatement(sql);           
                pstmt.setString(1, comboBoxNomes.getSelectedItem().toString());
                pstmt.executeUpdate();

                con.close();

                JOptionPane.showMessageDialog(this, "Reserva cancelada!", "", JOptionPane.INFORMATION_MESSAGE);
                //DISPOSE WINDOW
                parent.setEnabled(true);
                parent.toFront();
                this.dispose();
            }
            else{                
                JOptionPane.showMessageDialog(this, "Selecione os dados da lista", "Erro", JOptionPane.ERROR_MESSAGE);      
            }

        }
        catch(SQLException ex){
            
        }
    }//GEN-LAST:event_removerPorNomeActionPerformed

    private void buscarDadosNomesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscarDadosNomesActionPerformed
        try{
            Connection con = DriverManager.getConnection("jdbc:derby://localhost:1527/Hotel", "root", "123456" );

            PreparedStatement nomesQuery = con.prepareStatement("SELECT * FROM ROOT.quartos WHERE ocupado=true AND cliente!=''");            
            ResultSet nomesrs = nomesQuery.executeQuery();

            comboBoxNomes.removeAllItems();

            while(nomesrs.next()){
                comboBoxNomes.addItem(nomesrs.getString("cliente"));
            }

            con.close();
        }
        catch(SQLException ex){

        }
    }//GEN-LAST:event_buscarDadosNomesActionPerformed

    private void comboBoxNomesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboBoxNomesActionPerformed
        String nrsDosQuartos = "";
        
        try{
            Connection con = DriverManager.getConnection("jdbc:derby://localhost:1527/Hotel", "root", "123456" );

            PreparedStatement nomesQuery = con.prepareStatement("SELECT * FROM ROOT.quartos WHERE cliente=?");
            nomesQuery.setString(1, comboBoxNomes.getSelectedItem().toString());
            ResultSet nomesrs = nomesQuery.executeQuery();     
            while(nomesrs.next()){
                nrsDosQuartos += " " + nomesrs.getString("numero");
                
            }
            
            labelNrDoQuarto.setText(nrsDosQuartos);
            
            con.close();
        }
        catch(SQLException ex){

        }        
    }//GEN-LAST:event_comboBoxNomesActionPerformed

    private void comboBoxNrQuartoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboBoxNrQuartoActionPerformed
        String nome = "";
        
        try{
            Connection con = DriverManager.getConnection("jdbc:derby://localhost:1527/Hotel", "root", "123456" );

            PreparedStatement numeroQuery = con.prepareStatement("SELECT * FROM ROOT.quartos WHERE numero=?");
            numeroQuery.setString(1, comboBoxNrQuarto.getSelectedItem().toString());
            ResultSet nomesrs = numeroQuery.executeQuery();     
            
            nomesrs.next();
            nome = nomesrs.getString("cliente");
            
            labelNomeDoCliente.setText(nome);
            
            con.close();
        }
        catch(SQLException ex){

        }
    }//GEN-LAST:event_comboBoxNrQuartoActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buscarDadosNomes;
    private javax.swing.JButton buscarDadosNrQuarto;
    private javax.swing.JComboBox<String> comboBoxNomes;
    private javax.swing.JComboBox<String> comboBoxNrQuarto;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel labelNomeDoCliente;
    private javax.swing.JLabel labelNrDoQuarto;
    private javax.swing.JPanel porNome;
    private javax.swing.JPanel porQuarto;
    private javax.swing.JButton removerPorNome;
    private javax.swing.JButton removerPorNrQuarto;
    // End of variables declaration//GEN-END:variables
}
