/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package javaapplication1;

import java.awt.Component;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.time.LocalDate;
import java.time.ZoneId;
import java.util.List;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.Locale;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author Thiago Vinícius
 */
public class NovaReserva extends javax.swing.JFrame {
    
    JFrame parent;
    
   
    public NovaReserva(JFrame parent) {
        this.parent = parent;
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        comboBoxNomes = new javax.swing.JComboBox<>();
        novoCliente = new javax.swing.JButton();
        buscarDados = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        comboBoxNrQuarto = new javax.swing.JComboBox<>();
        efetuarReserva = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        dataInicial = new org.jdesktop.swingx.JXDatePicker();
        dataFinal = new org.jdesktop.swingx.JXDatePicker();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setAlwaysOnTop(true);
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                onWindowClosed(evt);
            }
        });

        jLabel1.setText("Nome do Cliente");

        comboBoxNomes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboBoxNomesActionPerformed(evt);
            }
        });

        novoCliente.setText("Adicionar Novo Cliente");
        novoCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                novoClienteActionPerformed(evt);
            }
        });

        buscarDados.setText("Buscar Dados");
        buscarDados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscarDadosActionPerformed(evt);
            }
        });

        jLabel2.setText("Nr. do Quarto:");

        comboBoxNrQuarto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboBoxNrQuartoActionPerformed(evt);
            }
        });

        efetuarReserva.setText("Efetuar Reserva");
        efetuarReserva.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                efetuarReservaActionPerformed(evt);
            }
        });

        jLabel3.setText("Data Inicial:");

        jLabel4.setText("Data Final:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(198, 198, 198)
                        .addComponent(buscarDados))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(18, 18, 18)
                                .addComponent(comboBoxNomes, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(novoCliente))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel4))
                                .addGap(25, 25, 25)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(dataFinal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(dataInicial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(comboBoxNrQuarto, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(176, 176, 176)
                        .addComponent(efetuarReserva, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(buscarDados, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(comboBoxNomes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(novoCliente))
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(comboBoxNrQuarto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(dataInicial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(dataFinal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(52, 52, 52)
                .addComponent(efetuarReserva, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void onWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_onWindowClosed
        parent.setEnabled(true);
        parent.toFront();
    }//GEN-LAST:event_onWindowClosed

    private void novoClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_novoClienteActionPerformed
        this.setEnabled(false);
        AdicionarCliente ac = new AdicionarCliente(this);
        ac.setVisible(true);
    }//GEN-LAST:event_novoClienteActionPerformed

    private void comboBoxNomesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboBoxNomesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboBoxNomesActionPerformed

    private void buscarDadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscarDadosActionPerformed
              
        try{
            Connection con = DriverManager.getConnection("jdbc:derby://localhost:1527/Hotel", "root", "123456" );
            
            PreparedStatement nomesQuery = con.prepareStatement("SELECT * FROM ROOT.clientes");
            PreparedStatement quartosQuery = con.prepareStatement("SELECT numero FROM ROOT.quartos WHERE ocupado = false");
            ResultSet nomesrs = nomesQuery.executeQuery();            
            ResultSet quartosrs = quartosQuery.executeQuery(); 
            
            comboBoxNomes.removeAllItems();
            comboBoxNrQuarto.removeAllItems();
            
            while(nomesrs.next()){
                
                comboBoxNomes.addItem(nomesrs.getString("nome"));
            }
            
            while(quartosrs.next()){
                
                comboBoxNrQuarto.addItem(quartosrs.getString("numero"));
            }
            
            con.close();
        }
        catch(SQLException ex){
            
        }
        
        
    }//GEN-LAST:event_buscarDadosActionPerformed

    private void comboBoxNrQuartoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboBoxNrQuartoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboBoxNrQuartoActionPerformed

    private void efetuarReservaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_efetuarReservaActionPerformed
        //set calendars
        LocalDate iCal = null;
        LocalDate fCal = null;
        try{
            if(dataInicial.getDate() != null && dataFinal.getDate() != null 
               && comboBoxNomes.getSelectedItem() != null && comboBoxNrQuarto.getSelectedItem() !=null){
                
                iCal = dataInicial.getDate().toInstant().atZone(ZoneId.systemDefault()).toLocalDate();
                fCal = dataFinal.getDate().toInstant().atZone(ZoneId.systemDefault()).toLocalDate();
                
                if(iCal.isBefore(fCal) && (iCal.isAfter(LocalDate.now()) || iCal.isEqual(LocalDate.now()))){
                    Connection con = DriverManager.getConnection("jdbc:derby://localhost:1527/Hotel", "root", "123456");

                    String sql = "UPDATE quartos SET ocupado=true, cliente=?, data_inicial=?, data_final=? WHERE numero=?";
                    PreparedStatement st = con.prepareStatement(sql);
                    st.setString(1, comboBoxNomes.getSelectedItem().toString());
                    st.setString(2, java.sql.Date.valueOf(iCal).toString());
                    st.setString(3, java.sql.Date.valueOf(fCal).toString());
                    st.setString(4, comboBoxNrQuarto.getSelectedItem().toString());
                    st.executeUpdate();
                    
                    
                    JOptionPane.showMessageDialog(this, "Reserva Efetuada com Sucesso!", "", JOptionPane.INFORMATION_MESSAGE);
                    parent.setEnabled(true);
                    parent.toFront();
                    this.dispose();
                }
                else{
                    JOptionPane.showMessageDialog(this, "Datas incorretas", "Erro", JOptionPane.ERROR_MESSAGE);                    
                }
            }

            else{
                JOptionPane.showMessageDialog(this, "Favor inserir todos os dados corretamente", "Erro", JOptionPane.ERROR_MESSAGE);
            }        
        }
        catch(SQLException ex){
            
        }
        
        
        
        
    }//GEN-LAST:event_efetuarReservaActionPerformed

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buscarDados;
    private javax.swing.JComboBox<String> comboBoxNomes;
    private javax.swing.JComboBox<String> comboBoxNrQuarto;
    private org.jdesktop.swingx.JXDatePicker dataFinal;
    private org.jdesktop.swingx.JXDatePicker dataInicial;
    private javax.swing.JButton efetuarReserva;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JButton novoCliente;
    // End of variables declaration//GEN-END:variables
}
